### ISSUE TITLE
No Slots Available

### ISSUE THREAD

**Issue by Aiturriaga** [kevin-vaghasiya/slot-booking-gas#2]
there is an error in the code the position of the array is wrong.
in this case in "calData" I should have placed a 5 otherwise the application crashes.
![image](https://user-images.githubusercontent.com/91960271/192824319-2d1f1b27-73d2-40c0-a4e2-525317eab113.png)

Once corrected, I was able to select a day without the application crashing, but the enabled days do not appear.
![image](https://user-images.githubusercontent.com/91960271/192824992-ef427351-9812-4393-9cc9-08a606f03866.png)

**Comment by Aiturriaga** [comment]
I have solved it, ignore the previous code. no change should be made. in the calendar ID, the ID OF THE ALREADY CREATED CALENDAR must be placed, I was placing the project id.

**Comment by kevin-vaghasiya** [comment]
@Aiturriaga  Thank You for using the Slot booking system.
